columnSuffix: null
contentColumnType: string
fieldGroup: 39d0cb62-72fb-4108-8557-4baf70657635 # Common
handle: components
instructions: ''
name: Components
searchable: false
settings:
  contentTable: '{{%matrixcontent_components}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
