columnSuffix: null
contentColumnType: string
fieldGroup: 39d0cb62-72fb-4108-8557-4baf70657635 # Common
handle: image
instructions: ''
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:0378e9ff-f828-4059-96a3-1ed548a26f1d' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:532e1def-e63e-48a3-960d-72896d7e0d3e' # Hero images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:0378e9ff-f828-4059-96a3-1ed548a26f1d' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
