columnSuffix: lukdemkb
contentColumnType: text
fieldGroup: c4ecfeb5-b217-4b6a-9a7a-f3c69ab06197 # Bets
handle: referralLinkTitle
instructions: ''
name: 'Referral link title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
