columnSuffix: vyhsazkz
contentColumnType: text
fieldGroup: 39d0cb62-72fb-4108-8557-4baf70657635 # Common
handle: seo
instructions: ''
name: SEO
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
