dateModified: 1662923712
email:
  fromEmail: seregars17@gmail.com
  fromName: test_craft
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0bf0fc28-186a-4fe0-9d96-ae4ea7c883e8: Default # Default
    0cbf3dde-519b-4406-ad2c-40b4aaddf3b7: 'Entry link' # Entry link
    1c8100fa-72d2-459c-be52-0f7311264d58: Body # Body
    1cea1829-26fd-4c78-8acc-7867b759922f: 'Video link' # Video link
    1e84a607-6e99-438c-9e37-4badea77bbd7: Partners # Partners
    3a63a2f3-14bb-4bad-9242-0f9575ccdac0: 'Referral link' # Referral link
    3b71240a-a80c-4791-9cc7-73372cd2755c: 'Footer links' # Footer links
    5f89d24d-d064-4829-a666-943b13de6161: 'News articles' # News articles
    7b19de37-5d1f-4185-804a-c6f5070b5356: __blank__ # __blank__
    7e98d1b7-a3a6-4b40-900c-30c91ad52318: 'Content blocks' # Content blocks
    8b48d4ae-04e6-467a-a8e8-bfbd19d5f684: Partners # Partners
    8c6834ff-c270-46b8-b1dc-915513b34013: 'Bets list' # Bets list
    8e6dc501-8c08-47d9-b875-e3e3048fdff5: URL # URL
    9aca1901-83d9-4641-a5a8-7d0a9269cd81: Hero # Hero
    9bb955cf-0a26-48c6-84d4-44eaae2b59b4: Default # Default
    9dd3b616-ffe6-434c-808f-5f337cd5f680: 'Bets entries' # Bets entries
    20c2dd83-73a2-41cc-89ae-597b0d685460: 'Game selector' # Game selector
    28c19995-f088-440a-b942-309b70972457: __blank__ # __blank__
    31fc4cda-180d-44cf-9649-e6d2311deb12: Default # Default
    34a1a262-790d-4280-829a-c0696be9a68f: 'Games list' # Games list
    35d9ce25-b7c4-4a3a-8ce0-fef7a33cccd2: Title # Title
    39d0cb62-72fb-4108-8557-4baf70657635: Common # Common
    42c66d97-53e0-4ccb-990d-52f558ad32e1: Title # Title
    49c98acd-34e2-497d-b653-43818f3ef595: News # News
    54a604b4-cb0c-412b-b024-1ce6b48f8ecf: Description # Description
    63aa0a94-a680-4523-bf36-dbadbf4c97ef: 'Entry link' # Entry link
    93a1ea6c-0014-4941-b815-84b2bc9a63b5: 'Background image' # Background image
    97c5a869-44a1-4fed-b944-b4d211a717ba: Media # Media
    104fe2e3-d47a-4ac9-af0f-9eb91f5e5f6c: 'Categories list' # Categories list
    0378e9ff-f828-4059-96a3-1ed548a26f1d: Images # Images
    389ec0bc-e750-4cca-b4cc-c3896f811c3e: 'Main navigation' # Main navigation
    532e1def-e63e-48a3-960d-72896d7e0d3e: 'Hero images' # Hero images
    736b3c6e-9604-481c-8e73-df06fc46ca78: test_craft # test_craft
    917fb507-17c6-428b-bb37-8f248596b1c2: 'Rich text' # Rich text
    947fa6fc-1184-4c14-8baf-64c9c519270c: 'Referral link title' # Referral link title
    752392a2-d375-4c05-a7ad-32c1e099207e: 'Linked entry' # Linked entry
    801157a5-ffa6-401b-b223-29f8bc9bf848: betscybersport.local # betscybersport.local
    9888806a-0fd5-47a9-9d36-fa428742f405: Home # Home
    44409646-b19b-43ab-9d2b-e80c1bf6bb76: News # News
    a0aa4c88-d77f-44c7-b3f6-17589266cdf0: Home # Home
    a0b723ba-1262-45bb-b901-b02ca8d48f58: Bets # Bets
    a6c468ec-424b-464d-801b-a4b603b6053b: Banner # Banner
    a64b5eb0-4982-435e-8cb7-003cd6156a7d: Image # Image
    be674ddd-a4f4-4e60-ac97-ceb8d850f53f: Socials # Socials
    c4ecfeb5-b217-4b6a-9a7a-f3c69ab06197: Bets # Bets
    ce58208f-1800-4109-b849-794e98ca2489: Form # Form
    d5960fed-19a3-433c-9602-c34cf6e06ec1: 'Bets link' # Bets link
    e7ea8641-7bba-4dc7-9827-283f3b07b2b1: Title # Title
    f70dabb6-7523-469a-9385-c6b735c541dd: Default # Default
plugins:
  freeform:
    edition: lite
    enabled: true
    licenseKey: GQAL7G59WE6U9D2JYAK734T5
    schemaVersion: 3.6.4
    settings:
      ajaxByDefault: true
      alertNotificationRecipients: ''
      autoScroll: true
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      bypassSpamCheckOnLoggedInUsers: false
      clientDigestFrequency: 1
      clientDigestRecipients: ''
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: ''
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      exportHandlesAsNames: false
      exportLabels: false
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formFieldShowOnlyAllowedForms: false
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: flexbox.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: false
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: ''
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaLazyLoad: false
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      rememberPageSubmitOrder: true
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: pointers
      sessionContext: payload
      sessionContextCount: 100
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: 180
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: true
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      successTemplateDirectory: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: true
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
system:
  edition: solo
  live: true
  name: test_craft
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
