defaultPlacement: end
enableVersioning: true
handle: categoriesList
name: 'Categories list'
propagationMethod: all
siteSettings:
  801157a5-ffa6-401b-b223-29f8bc9bf848: # betscybersport.local
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 6173cc15-ecba-4b8e-8958-af3f7b75a02e
type: structure
