defaultPlacement: end
enableVersioning: true
handle: footerLinks
name: 'Footer links'
propagationMethod: all
siteSettings:
  801157a5-ffa6-401b-b223-29f8bc9bf848: # betscybersport.local
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 3a10ef20-e337-4b80-9d9d-2d2e2aac9cb1
type: structure
