defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  801157a5-ffa6-401b-b223-29f8bc9bf848: # Betscybersport
    enabledByDefault: true
    hasUrls: true
    template: templates/home/home.twig
    uriFormat: __home__
type: single
