defaultPlacement: end
enableVersioning: true
handle: news
name: News
propagationMethod: all
siteSettings:
  801157a5-ffa6-401b-b223-29f8bc9bf848: # betscybersport.local
    enabledByDefault: true
    hasUrls: true
    template: templates/news/index.twig
    uriFormat: news
type: single
