defaultPlacement: end
enableVersioning: true
handle: partners
name: Partners
propagationMethod: all
siteSettings:
  801157a5-ffa6-401b-b223-29f8bc9bf848: # betscybersport.local
    enabledByDefault: true
    hasUrls: true
    template: templates/partners/partners.twig
    uriFormat: partners
type: single
